; ----------------------------------------------------------------------
; General Options

Drive1=C
Drive2=E
Drive3=F
NetworkMaxDownload=1000000
NetworkMaxUpload=500000
SystemGraphType=Floating
CalendarShowEvents=1
CalendarExtraDays=1
CalendarLeadingZeroes=0
CalendarMondays=0
GallerySubfolders=1
GalleryPosition=Center
GalleryRatio=3/4
VolumeIncrement=5
TriptychInterval=30
TriptychDisabled=0
ProcessInterval=5