; ----------------------------------------------------------------------
; LWA SUITE THEME
; Primary Color Scheme -> https://www.schemecolor.com/fill-the-void.php
; Secondary Color Scheme -> https://www.schemecolor.com/sun-gradient.php

[Variables]
primaryFont="Love Marker"
secondaryFont="Bombing"
supportFont="Rubik"

defColor1=16,23,91
defColor2=71,34,97
defColor3=131,63,114
defColor4=246,151,141
defColor5=255,207,179

secColor1=250,134,7
secColor2=250,150,27
secColor3=252,176,51
secColor4=254,204,81
secColor5=255,228,105
secColor6=255,245,123
